FROM python:3.9.16-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*
COPY . .
ENV CRONMONITORING=yourcronmonitoringurl
RUN pip install -r requirements.txt
CMD ["python", "grabber.py"]